---
# main.yml

- include_vars: "{{ansible_distribution_release }}.yml"

- name: Set up xorg.conf.d
  file:
    path: "{{ x11_config_path }}"
    state: directory

- include_tasks: "{{ ansible_os_family | lower }}/packages.yml"
- include_tasks: "{{ ansible_os_family | lower }}/lirc.yml"
  when: ansible_distribution_version < '18.04'
- include_tasks: "{{ ansible_os_family | lower }}/network.yml"
  when: ansible_distribution_version < '18.04'

- include_tasks: "{{ ansible_os_family | lower }}/ir-keytable.yml"
  when: ansible_distribution_version >= '18.04'

- include_tasks: autosuspend.yml
  when: suspend

- include_tasks: drivers/{{ display_driver.type }}.yml

- include_tasks: setup.yml
- include_tasks: "{{ ansible_os_family | lower }}/desktop.yml"
